version: "3.3"

services:
  database:
    container_name: curso_django_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=3284
      - POSTGRES_USER=david
    ports:
      - 5432