# Generated by Django 4.0.6 on 2022-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(verbose_name='Fim')),
            ],
        ),
    ]
