# Generated by Django 4.0.5 on 2022-07-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=32, verbose_name='slug'),
        ),
    ]
