# Generated by Django 4.0.5 on 2022-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, verbose_name='slug')),
                ('titulo', models.CharField(max_length=32, verbose_name='Titulo')),
                ('vimeo_id', models.CharField(max_length=32, verbose_name='Vimeo ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em: ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em: ')),
            ],
        ),
    ]
